version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      backend:
        ipv4_address: 172.23.0.3
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    networks:
      - backend

volumes:
  pgdata:
    driver: local

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
